CREATE TABLE data_source (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, DataType varchar, URL varchar, PollingInterval int);
CREATE TABLE config (key varchar, value varchar);
CREATE TABLE alert_sink (Id int PRIMARY KEY, type varchar, URL varchar);
CREATE TABLE time_chunk (service_Id int, indicator_Id int, "timestamp" TIMESTAMP(0) WITH TIME ZONE, chunk bytea);
CREATE TABLE service (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" varchar, prometheus_url varchar, load_query varchar, latency_query varchar, interval_seconds int);
CREATE TABLE verdict (SampleTimestamp int, Good boolean, Pvalue float);
