CREATE TABLE IF NOT EXISTS service (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar,
    prometheus_url varchar,
    load_query varchar,
    latency_query varchar,
    interval_seconds int
);
