# SPDX-FileCopyrightText: 2026 Uncertain Tea Inc.
# SPDX-License-Identifier: LicenseRef-PolyForm-Internal-Use-1.0.0

# This is an example configuration for the database created for testing purposes.
database: postgresql
connection_string: example
